In [2]:
import numpy as np

In [3]:
#1. Create a 1D array of numbers from 0 to 9
my_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(my_1d)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#2. Create a 3×3 NumPy array of all Boolean value Trues
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
#3. Extract all odd numbers from array of 1-10
slice = np.array([1,2,3,4,5,6,7,8,9,10]) 
# slices from 1 to 8 in increments of 1
print(slice[0:10:2])

[1 3 5 7 9]


In [9]:
#4. Replace all odd numbers in an array of 1-10 with the value -1
eny_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_values = (eny_array%2 == 1) 
eny_array[odd_values] = -1 

print(eny_array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [11]:
#5. Convert a 1D array to a 2D array with 2 rows
a1d = np.array([1,2,3,4,5,6])
a2d = np.reshape(a1d, (-1, 2))

print(a2d)


[[1 2]
 [3 4]
 [5 6]]


In [17]:
#6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
a = np.arange(20,29).reshape(3,3)
b = np.arange(30,39).reshape(3,3)
c = np.dot(a, b)

total_sum = np.sum(c)
print(c)

[[2085 2148 2211]
 [2382 2454 2526]
 [2679 2760 2841]]


In [19]:
sum = np.sum(c)
print(sum)

22086


In [ ]:
## Extension:
#1. Create the following pattern without hardcoding. Use only NumPy functions.



In [ ]:
#2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b


In [ ]:
#3. Get all items between 3 and 7 from a and b and sum themtogether